-- MySQL Script generated by MySQL Workbench
-- Sat Apr 28 15:35:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema libtaxidb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `libtaxidb` ;

-- -----------------------------------------------------
-- Schema libtaxidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libtaxidb` DEFAULT CHARACTER SET utf8 ;
USE `libtaxidb` ;

-- -----------------------------------------------------
-- Table `libtaxidb`.`RoleUzivatele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`RoleUzivatele` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`RoleUzivatele` (
  `idRoleUzivatele` INT NOT NULL AUTO_INCREMENT,
  `nazevRole` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoleUzivatele`),
  UNIQUE INDEX `idroleUzivatele_UNIQUE` (`idRoleUzivatele` ASC),
  UNIQUE INDEX `nazevRole_UNIQUE` (`nazevRole` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`Uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`Uzivatel` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`Uzivatel` (
  `idUzivatel` INT NOT NULL AUTO_INCREMENT,
  `nickName` VARCHAR(45) NOT NULL,
  `celeJmeno` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NULL,
  `veFirmeOd` DATE NULL,
  `ico` VARCHAR(45) NULL,
  `idRoleUzivatele` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `token` CHAR(16) NULL,
  `tokenExpire` DATETIME NULL,
  PRIMARY KEY (`idUzivatel`),
  UNIQUE INDEX `idUzivatel_UNIQUE` (`idUzivatel` ASC),
  UNIQUE INDEX `nickName_UNIQUE` (`nickName` ASC),
  UNIQUE INDEX `celeJmeno_UNIQUE` (`celeJmeno` ASC),
  INDEX `fk_Uzivatel_RoleUzivatele1_idx` (`idRoleUzivatele` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`TypPraceUzivatele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`TypPraceUzivatele` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`TypPraceUzivatele` (
  `idTypPraceUzivatele` INT NOT NULL AUTO_INCREMENT,
  `typPrace` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypPraceUzivatele`),
  UNIQUE INDEX `idTypPraceUzivatele_UNIQUE` (`idTypPraceUzivatele` ASC),
  UNIQUE INDEX `typPrace_UNIQUE` (`typPrace` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`StavUzivatele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`StavUzivatele` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`StavUzivatele` (
  `idStavUzivatele` INT NOT NULL AUTO_INCREMENT,
  `nazevStavu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStavUzivatele`),
  UNIQUE INDEX `idStavUzivatele_UNIQUE` (`idStavUzivatele` ASC),
  UNIQUE INDEX `nazevSTavu_UNIQUE` (`nazevStavu` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`Auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`Auto` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`Auto` (
  `idAuto` INT NOT NULL AUTO_INCREMENT,
  `znacka` VARCHAR(45) NOT NULL,
  `typ` VARCHAR(45) NULL,
  `barva` VARCHAR(45) NOT NULL,
  `rokVyroby` INT NULL,
  `pocetMist` INT NOT NULL,
  `idVysilacka` INT NULL,
  `cisloMagistratni` INT NULL,
  `registracniZnacka` VARCHAR(45) NULL,
  PRIMARY KEY (`idAuto`),
  UNIQUE INDEX `idAuto_UNIQUE` (`idAuto` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`Dochazka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`Dochazka` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`Dochazka` (
  `idDochazka` INT NOT NULL AUTO_INCREMENT,
  `prichod` DATETIME NOT NULL,
  `odchod` DATETIME NULL DEFAULT NULL,
  `idUzivatel` INT NOT NULL,
  `idTypPraceUzivatele` INT NOT NULL,
  `idStavUzivatele` INT NOT NULL,
  `idAuto` INT NOT NULL,
  PRIMARY KEY (`idDochazka`),
  UNIQUE INDEX `idDochazka_UNIQUE` (`idDochazka` ASC),
  INDEX `fk_Dochazka_Uzivatel_idx` (`idUzivatel` ASC),
  INDEX `fk_Dochazka_TypPraceUzivatele1_idx` (`idTypPraceUzivatele` ASC),
  INDEX `fk_Dochazka_StavUzivatele1_idx` (`idStavUzivatele` ASC),
  INDEX `fk_Dochazka_Auto1_idx` (`idAuto` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`LogStavu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`LogStavu` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`LogStavu` (
  `idLogStavu` INT NOT NULL AUTO_INCREMENT,
  `idStavUzivatele` INT NOT NULL,
  `idUzivatel` INT NOT NULL,
  `cas` DATETIME NOT NULL,
  PRIMARY KEY (`idLogStavu`),
  UNIQUE INDEX `idLogStavu_UNIQUE` (`idLogStavu` ASC),
  INDEX `fk_LogStavu_StavUzivatele1_idx` (`idStavUzivatele` ASC),
  INDEX `fk_LogStavu_Uzivatel1_idx` (`idUzivatel` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`StavObjednavky`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`StavObjednavky` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`StavObjednavky` (
  `idStavObjednavky` INT NOT NULL AUTO_INCREMENT,
  `nazevStavu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStavObjednavky`),
  UNIQUE INDEX `idStavObjednavky_UNIQUE` (`idStavObjednavky` ASC),
  UNIQUE INDEX `nazevStavu_UNIQUE` (`nazevStavu` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`Objednavka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`Objednavka` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`Objednavka` (
  `idObjednavka` INT NOT NULL AUTO_INCREMENT,
  `idStavObjednavky` INT NOT NULL,
  `idDochazka` INT NOT NULL,
  `adresaKam` VARCHAR(100) NOT NULL,
  `pocetAut` INT NOT NULL DEFAULT 1,
  `casVzniku` DATETIME NOT NULL,
  `casPristaveniVozu` DATETIME NOT NULL,
  `casVyrizeni` DATETIME NULL,
  `kontaktNaKlienta` VARCHAR(45) NULL,
  PRIMARY KEY (`idObjednavka`),
  UNIQUE INDEX `idObjednavka_UNIQUE` (`idObjednavka` ASC),
  INDEX `fk_Objednavka_StavObjednavky1_idx` (`idStavObjednavky` ASC),
  INDEX `fk_Objednavka_DochazkaRidicu1_idx` (`idDochazka` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `libtaxidb`.`Hodnoceni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libtaxidb`.`Hodnoceni` ;

CREATE TABLE IF NOT EXISTS `libtaxidb`.`Hodnoceni` (
  `idHodnoceni` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NULL,
  `znamka` INT NULL,
  `idObjednavka` INT NOT NULL,
  PRIMARY KEY (`idHodnoceni`),
  UNIQUE INDEX `idHodnoceni_UNIQUE` (`idHodnoceni` ASC),
  INDEX `fk_Hodnoceni_Objednavka1_idx` (`idObjednavka` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
